update

diff --git a/mksync b/mksync
--- a/mksync
+++ b/mksync
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-# TODO: allow pinning versions
-
 # $1  slug/id
 # $2? game version
 # $3? loader
@@ -78,12 +76,38 @@ other() {
     }"
 }
 
+pinned() {
+  version="${1##* }"
+  path="${1%% *}"
+
+  printf '%-48s %b' "$path" "${version} ?" 1>&2
+  resp="$(wget -q -O - "https://api.modrinth.com/v2/version/${version}")"
+
+  if [ "$resp" == "null" ]; then
+    printf '%b\n' " not found!" 1>&2
+    exit 1
+  else
+    printf '%b\n' " found!" 1>&2
+  fi
+
+  printf '%b' "$resp" \
+    | jq -r "{
+    url: .files[0].url,
+    name: \"${path##*/}\",
+    version: .id,
+    type: \"${path%%/*}\"
+    }"
+}
+
 {
   cat content.json
   # fetch latest from content from modrinth API
   while read -r line; do
+    [ -z "$line" ] && continue;
+
     case "$line" in
       "#"*)  continue;;
+      *" "*) pinned "$line";;
       mod/*) mod   "$line";;
       *)     other "$line";;
     esac
